#!/bin/bash
# GitHub Skill — Clone, Branch, Commit, PR
# Called by coder agent via exec tool
# Requires: gh CLI authenticated, GITHUB_TOKEN env var
#
# Usage:
#   ./github.sh clone <repo_url> <workspace_dir>
#   ./github.sh branch <workspace_dir> <branch_name>
#   ./github.sh commit <workspace_dir> <message>
#   ./github.sh pr <workspace_dir> <title> <body> <base_branch>
#   ./github.sh list-repos

set -euo pipefail

ACTION="${1:?Usage: github.sh <action> [args...]}"
shift

case "$ACTION" in
  clone)
    REPO="${1:?repo_url required}"
    DIR="${2:?workspace_dir required}"
    gh repo clone "$REPO" "$DIR" -- --depth=1
    echo "Cloned $REPO → $DIR"
    ;;

  branch)
    DIR="${1:?workspace_dir required}"
    BRANCH="${2:?branch_name required}"
    cd "$DIR"
    git checkout -b "$BRANCH"
    echo "Created branch: $BRANCH"
    ;;

  commit)
    DIR="${1:?workspace_dir required}"
    MSG="${2:?commit message required}"
    cd "$DIR"
    git add -A
    git commit -m "$MSG"
    git push origin HEAD
    echo "Committed and pushed: $MSG"
    ;;

  pr)
    DIR="${1:?workspace_dir required}"
    TITLE="${2:?PR title required}"
    BODY="${3:-Auto-generated by OpenClaw bot employee}"
    BASE="${4:-main}"
    cd "$DIR"
    gh pr create --title "$TITLE" --body "$BODY" --base "$BASE"
    ;;

  list-repos)
    gh repo list --limit 50 --json nameWithOwner,description --jq '.[] | "\(.nameWithOwner) — \(.description // "no description")"'
    ;;

  ci-status)
    DIR="${1:?workspace_dir required}"
    cd "$DIR"
    BRANCH=$(git branch --show-current)
    gh run list --branch "$BRANCH" --limit 1 --json status,conclusion,name --jq '.[0]'
    ;;

  ci-logs)
    DIR="${1:?workspace_dir required}"
    cd "$DIR"
    RUN_ID=$(gh run list --branch "$(git branch --show-current)" --limit 1 --json databaseId --jq '.[0].databaseId')
    gh run view "$RUN_ID" --log-failed 2>/dev/null || gh run view "$RUN_ID" --log | tail -100
    ;;

  review)
    DIR="${1:?workspace_dir required}"
    PR="${2:-}"
    cd "$DIR"
    if [ -n "$PR" ]; then
      gh pr diff "$PR" | head -500
      echo ""
      echo "--- PR Info ---"
      gh pr view "$PR" --json title,body,author,additions,deletions,changedFiles --jq '{title, author: .author.login, additions, deletions, changedFiles, body: (.body[:300])}'
    else
      # Review latest PR
      gh pr diff | head -500
      echo ""
      gh pr view --json title,body,author,additions,deletions,changedFiles --jq '{title, author: .author.login, additions, deletions, changedFiles, body: (.body[:300])}'
    fi
    ;;

  diff)
    DIR="${1:?workspace_dir required}"
    FILE="${2:-}"
    cd "$DIR"
    if [ -n "$FILE" ]; then
      git diff HEAD -- "$FILE"
    else
      git diff HEAD --stat
      echo ""
      git diff HEAD
    fi
    ;;

  merge)
    DIR="${1:?workspace_dir required}"
    PR="${2:-}"
    cd "$DIR"
    if [ -n "$PR" ]; then
      gh pr merge "$PR" --squash --auto
    else
      gh pr merge --squash --auto
    fi
    ;;

  pr-list)
    DIR="${1:?workspace_dir required}"
    cd "$DIR"
    gh pr list --state open --json number,title,author,createdAt,headRefName --jq '.[] | "#\(.number) [\(.author.login)] \(.title) (\(.headRefName))"'
    ;;

  *)
    echo "Unknown action: $ACTION"
    echo "Available: clone, branch, commit, pr, list-repos, ci-status, ci-logs, review, diff, merge, pr-list"
    exit 1
    ;;
esac
